version: "3.7"

services:

  proxy:
    image: tourgeek/envoy:${DOCKER_FLOW_PROXY_TAG:-latest}
    ports:
    - 8080:80
    - 8001:8001
    networks:
    - proxy
    deploy:
      replicas: 1

networks:
  proxy:
    external: true
