version: "3.7"

services:

  proxy:
    image: tourgeek/envoy:${DOCKER_FLOW_PROXY_TAG:-latest}
    ports:
    - 8000:80
    - 8001:8001
    networks:
    - proxy
    deploy:
      replicas: 1

  web_service:
    image: citizenstig/httpbin:${DOCKER_FLOW_SWARM_LISTENER_TAG:-latest}
#   image: solsson/http-echo:${DOCKER_FLOW_SWARM_LISTENER_TAG:-latest}
    networks:
    - proxy
    ports:
#    - 8080:80
    - 8080:8000
    deploy:
      replicas: 1

networks:
  proxy:
    external: true
